apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "structurizr.fullname" . }}-tomcat-server-properties-cm
  labels:
    {{- include "structurizr.labels" . | nindent 4 }}
data:
  tomcat_server: |-
{{- .Values.tomcat_server | nindent 6 }}
